apiVersion: apps/v1
kind: Deployment
metadata:
  name: tour-app
  labels:
    app: tour-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tour-app
  template:
    metadata:
      labels:
        app: tour-app
    spec:
      containers:
      - name: tour-app
        image: yourusername/tour-app:latest
        ports:
        - containerPort: 3000
        # optionally, env vars, livenessProbe, readinessProbe etc.
